# Regenerate analysis file monthly or when apriory is changed

name: Generate analysis files v18

on:
  push:
    # when module merges are added to apriori, this
    # might cause changes in the analysis
    paths: ["openupgrade_scripts/apriori.py"]
#  schedule:
#    # first monday in month
#    - cron: "0 4 1-8 * 1"

env:
  FROM_VERSION: "17.0"
  TO_VERSION: "18.0"

jobs:
  generate-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install required packages
        run: |
          sudo apt update
          sudo apt install \
              expect \
              expect-dev \
              libevent-dev \
              libldap2-dev \
              libsasl2-dev \
              libxml2-dev \
              libxslt1-dev \
              nodejs \
              python3-lxml \
              python3-passlib \
              python3-psycopg2 \
              python3-serial \
              python3-simplejson \
              python3-werkzeug \
              python3-yaml \
              unixodbc-dev
      - name: Checkout previous OpenUpgrade
        uses: actions/checkout@v4
        with:
          ref: "${{ env.FROM_VERSION }}"
          path: openupgrade-${{ env.FROM_VERSION }}
      - name: Checkout OpenUpgrade from current branch
        uses: actions/checkout@v4
        with:
          path: openupgrade-${{ env.TO_VERSION }}
      - name: Install previous Odoo
        run: |
          wget -q -O- https://github.com/oca/ocb/archive/refs/heads/$FROM_VERSION.tar.gz | tar -xz
          wget -q -O- https://github.com/oca/server-tools/archive/refs/heads/$FROM_VERSION.tar.gz | tar -xz
          python -mvenv env-$FROM_VERSION
          . env-$FROM_VERSION/bin/activate
          pip install OCB-$FROM_VERSION
          pip install -r server-tools-$FROM_VERSION/requirements.txt
          pip install -r openupgrade-$FROM_VERSION/requirements.txt
          odoo -c odoo-$FROM_VERSION.cfg --addons-path server-tools-$FROM_VERSION openupgrade-$FROM_VERSION --stop-after-init
      - name: Install current Odoo
        run: |
          wget -q -O- https://github.com/oca/ocb/archive/refs/heads/$TO_VERSION.tar.gz | tar -xz
          wget -q -O- https://github.com/oca/server-tools/archive/refs/heads/$TO_VERSION.tar.gz | tar -xz
          python -mvenv env-$TO_VERSION
          . env-$TO_VERSION/bin/activate
          pip install OCB-$TO_VERSION
          pip install -r server-tools-$TO_VERSION/requirements.txt
          pip install -r openupgrade-$TO_VERSION/requirements.txt
          odoo -c odoo-$TO_VERSION.cfg --addons-path server-tools-$TO_VERSION openupgrade-$TO_VERSION --stop-after-init
      - name: Create previous Odoo database
        env:
          ODOO: env-${{ env.FROM_VERSION }}/bin/odoo -c odoo-${{ env.FROM_VERSION }} -d ${{ env.FROM_VERSION }}
          ODOO_SHELL: env-${{ env.FROM_VERSION }}/bin/odoo shell -c odoo-${{ env.FROM_VERSION }} -d ${{ env.FROM_VERSION }}
        run: |
          $ODOO -i upgrade_analysis --stop-after-init
          $ODOO_SHELL <<EOF
          install_wizard = env['upgrade.install.wizard'].create({})
          install_wizard.select_odoo_modules()
          install_wizard.install_modules()
          env.cr.commit()
          EOF
          $ODOO_SHELL <<EOF
          env['upgrade.generate.record.wizard'].create({}).generate()
          env.cr.commit()
          EOF
      - name: Create current Odoo database
        env:
          ODOO: env-${{ env.TO_VERSION }}/bin/odoo -c odoo-${{ env.TO_VERSION }} -d ${{ env.TO_VERSION }}
          ODOO_SHELL: env-${{ env.TO_VERSION }}/bin/odoo shell -c odoo-${{ env.TO_VERSION }} -d ${{ env.TO_VERSION }}
        run: |
          $ODOO -i upgrade_analysis --stop-after-init
          $ODOO_SHELL <<EOF
          install_wizard = env['upgrade.install.wizard'].create({})
          install_wizard.select_odoo_modules()
          install_wizard.install_modules()
          env.cr.commit()
          EOF
          $ODOO_SHELL <<EOF
          env['upgrade.generate.record.wizard'].create({}).generate()
          env.cr.commit()
          EOF
      - uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          global: true
      - name: Delete all files to be generated from repository
        env:
          OPENUPGRADE_DIR: openupgrade-${{ env.TO_VERSION }}
        run: |
          for file in $OPENUPGRADE_DIR/openupgrade_scripts/scripts/*/*/{noupdate_changes.xml,upgrade_analysis.txt}; do
            if [ ! -f $file ]; then
              continue
            fi
            git -C $OPENUPGRADE_DIR rm --quiet ${file#$OPENUPGRADE_DIR/}
          done
      - name: Create analysis
        env:
          FROM_ODOO: env-${{ env.FROM_VERSION }}/bin/odoo -c odoo-${{ env.FROM_VERSION }} -d ${{ env.FROM_VERSION }}
          TO_ODOO_SHELL: env-${{ env.TO_VERSION }}/bin/odoo shell -c odoo-${{ env.TO_VERSION }} -d ${{ env.TO_VERSION }}
        run: |
          $FROM_ODOO --max-cron-threads=0 &
          ODOO_PID=$!
          $TO_ODOO_SHELL <<EOF
          config = env['upgrade.comparison.config'].create({
              'database': '${{ env.FROM_VERSION }}',
          })
          analysis_wizard = env['upgrade.analysis'].create({
              'config_id': config.id,
          })
          analysis_wizard._compute_upgrade_path()
          analysis_wizard.analyze()
          env.cr.commit()
          print(analysis_wizard.log)
          EOF
          kill -s KILL $ODOO_PID
      - name: Create PR
        uses: peter-evans/create-pull-request@v7
